DOCKER_REPO_PATH: yourpath
DOCKER_REPO_TAG: yourtag

DOCKER_REPO_USERNAME: username
DOCKER_REPO_PASSWORD: password
DOCKER_EMAIL: email

DOCKER_REPO_HOST: sdvl3prox001.td.tddb.com
DOCKER_REPO_PORT: 7001

USE_LOCAL_REGISTRY: true
USE_REMOTE_REGISTRY: false
